#!/usr/bin/env node

/**
 * ekkOS Blog Cover Image Generator
 * Uses Imagen 4 via Google Cloud Vertex AI
 *
 * Usage: node generate-cover.mjs <slug> "<prompt>"
 * Example: node generate-cover.mjs multi-agent-memory "Brain nodes with fragmentation"
 */

import { exec } from 'child_process';
import { promisify } from 'util';
import fs from 'fs/promises';
import path from 'path';
import { config } from 'dotenv';

// Load env - first .env.local, then root .env
config({ path: '/Volumes/MacMiniPort/DEV/EKKOS/apps/blog/.env.local' });
config({ path: '/Volumes/MacMiniPort/DEV/EKKOS/.env' });

const execAsync = promisify(exec);

// ============================================================================
// STANDARDIZED CONFIGURATION (DO NOT CHANGE)
// ============================================================================

const CONFIG = {
  // Using Imagen 4 via Vertex AI
  model: 'imagen-4.0-generate-001',
  imageModel: 'imagen-4.0-generate-001',

  // Image aspect ratio (16:9 for blog covers)
  aspectRatio: '16:9',

  // Logo configuration
  logo: {
    path: '/Volumes/MacMiniPort/DEV/LOGO/ekkos_white.png',
    size: '300x',
    gravity: 'SouthEast',
    offset: '+30+30'
  },

  // Output paths
  blogDir: '/Volumes/MacMiniPort/DEV/EKKOS/apps/blog',
  outputDir: '/Volumes/MacMiniPort/DEV/EKKOS/apps/blog/public/images/blog',

  // Vertex AI config
  apiKey: process.env.GOOGLE_VERTEX_AI_KEY,
  projectId: process.env.GOOGLE_VERTEX_PROJECT,
  location: process.env.GOOGLE_VERTEX_LOCATION || 'us-central1'
};

// ============================================================================
// GET ACCESS TOKEN (Vertex AI requires authentication)
// ============================================================================

async function getAccessToken() {
  try {
    const { stdout } = await execAsync('gcloud auth application-default print-access-token');
    return stdout.trim();
  } catch (error) {
    console.error('❌ Failed to get access token. Ensure gcloud is installed and authenticated:');
    console.error('   gcloud auth application-default login');
    process.exit(1);
  }
}

// ============================================================================
// GENERATE IMAGE WITH VERTEX AI
// ============================================================================

async function generateWithVertexAI(prompt, accessToken) {
  const url = `https://${CONFIG.location}-aiplatform.googleapis.com/v1/projects/${CONFIG.projectId}/locations/${CONFIG.location}/publishers/google/models/${CONFIG.imageModel}:predict`;

  const payload = {
    instances: [
      {
        prompt
      }
    ],
    parameters: {
      sampleCount: 1,
      aspectRatio: CONFIG.aspectRatio
    }
  };

  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(payload)
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Vertex AI error: ${response.status} - ${errorText}`);
    }

    const data = await response.json();

    if (!data.predictions || data.predictions.length === 0) {
      throw new Error('No images generated by Vertex AI');
    }

    // Extract base64 image data
    const base64Image = data.predictions[0].bytesBase64Encoded;
    if (!base64Image) {
      throw new Error('No bytesBase64Encoded in prediction response');
    }

    const buffer = Buffer.from(base64Image, 'base64');
    return buffer;
  } catch (error) {
    throw new Error(`Vertex AI generation failed: ${error.message}`);
  }
}

// ============================================================================
// MAIN FUNCTION
// ============================================================================

async function generateCover(slug, userPrompt) {
  console.log('🎨 ekkOS Blog Cover Generator');
  console.log('═'.repeat(60));
  console.log(`📝 Slug: ${slug}`);
  console.log(`💭 Prompt: ${userPrompt}`);
  console.log('');
  console.log('📐 Standardized Configuration:');
  console.log(`   Model: ${CONFIG.imageModel} (Imagen 4 via Vertex AI)`);
  console.log(`   Project: ${CONFIG.projectId}`);
  console.log(`   Location: ${CONFIG.location}`);
  console.log(`   Aspect Ratio: ${CONFIG.aspectRatio}`);
  console.log(`   Logo: ${CONFIG.logo.size} at ${CONFIG.logo.gravity} ${CONFIG.logo.offset}`);
  console.log('');

  if (!CONFIG.projectId) {
    console.error('❌ Missing Google Cloud Project ID. Check .env:');
    console.error('   - GOOGLE_VERTEX_PROJECT');
    process.exit(1);
  }

  const tempFile = path.join('/tmp', `imagen-${slug}-${Date.now()}.png`);
  const finalFile = path.join(CONFIG.outputDir, `${slug}.png`);

  try {
    // Step 1: Get access token
    console.log('⚡ Step 1: Authenticating with Google Cloud...');
    const accessToken = await getAccessToken();
    console.log('✓ Authentication successful');

    // Step 2: Generate image with Vertex AI
    console.log('');
    console.log('🖼️  Step 2: Generating image with Imagen 4...');

    // Enhanced prompt following Imagen 4 best practices
    // NOTE: Do NOT mention logos — ImageMagick composites the real logo afterward
    const enhancedPrompt =
      `${userPrompt}. ` +
      `Professional photorealistic 3D rendering with cinematic volumetric lighting. ` +
      `Dark gradient background with rich color depth. ` +
      `Ultra detailed, 16:9 landscape format.`;

    const imageBuffer = await generateWithVertexAI(enhancedPrompt, accessToken);
    await fs.writeFile(tempFile, imageBuffer);
    console.log(`✓ Image generated (${imageBuffer.length} bytes)`);

    // Step 3: Resize to 1920x1080 and composite logo
    console.log('');
    console.log('✨ Step 3: Resizing and compositing ekkOS logo...');

    await execAsync(
      `magick "${tempFile}" -resize 1920x1080^ -gravity center -extent 1920x1080 ` +
      `\\( "${CONFIG.logo.path}" -resize ${CONFIG.logo.size} \\) ` +
      `-gravity ${CONFIG.logo.gravity} -geometry ${CONFIG.logo.offset} ` +
      `-composite "${finalFile}"`
    );

    console.log('✓ Logo composited');

    // Step 4: Verify output
    console.log('');
    console.log('🔍 Step 4: Verifying output...');

    const stats = await fs.stat(finalFile);
    const fileSizeMB = (stats.size / 1024 / 1024).toFixed(2);

    // Get dimensions
    const { stdout: dims } = await execAsync(`magick identify -format "%wx%h" "${finalFile}"`);

    console.log('');
    console.log('═'.repeat(60));
    console.log('✅ SUCCESS');
    console.log('═'.repeat(60));
    console.log(`📁 Output: ${finalFile}`);
    console.log(`📊 Size: ${fileSizeMB} MB`);
    console.log(`📐 Dimensions: ${dims}`);
    console.log('');
    console.log('Verification Checklist:');
    console.log('  ✓ Model: Imagen 4 via Vertex AI');
    console.log('  ✓ Aspect Ratio: 16:9 (resized to 1920x1080)');
    console.log('  ✓ Logo: ekkOS white, 300px, lower-right');
    console.log('');
    console.log('Next steps:');
    console.log('  1. Preview the image');
    console.log('  2. Update blog post frontmatter');
    console.log('  3. Commit and deploy');

    // Cleanup temp file
    await fs.unlink(tempFile).catch(() => {});

  } catch (error) {
    console.error('');
    console.error('❌ ERROR:', error.message);
    console.error('');
    // Cleanup temp file on error
    await fs.unlink(tempFile).catch(() => {});
    process.exit(1);
  }
}

// ============================================================================
// CLI INTERFACE
// ============================================================================

const args = process.argv.slice(2);

if (args.length < 2) {
  console.error('Usage: node generate-cover.mjs <slug> "<prompt>"');
  console.error('');
  console.error('Example:');
  console.error('  node generate-cover.mjs multi-agent-memory "Central glowing brain surrounded by fragmented nodes"');
  console.error('');
  process.exit(1);
}

const [slug, prompt] = args;

generateCover(slug, prompt);
